function love.conf(t)
    t.identity = "outside"
    t.appendidentity = true
    t.window.title = "outside"
    t.window.icon = nil
    t.window.width = 1024
    t.window.height = 768
    t.modules.physics = false
    t.modules.touch = false
    t.modules.data = true
end